on:
  push:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: create-sonar-project
        uses: nelsoncanarinho/setup-sonar-action@v1.0.0
        with:
          SONAR_PROJECT_NAME: ${{ github.repository }}
          SONAR_ORGANIZATION: mlaraibyousaf
          # Name of the main branch of the project
          SONAR_DEFAULT_BRANCH: master
          # Sonar token used to integrate with SonarCloud api.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
