on:
  push:
    branches:
      - main
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup SonarCloud
        uses: nelsoncanarinho/setup-sonar@v1.0.0
        with:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
