on:
  push:
    branches:
      - master
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: create-sonar-project
        uses: nelsoncanarinho/setup-sonar-action@v1.0.0
        with:
          # Sonar custom name for the project. Default is the repo name.
          SONAR_PROJECT_NAME: speech-emotion
          # Sonar custom project key. Default is the repo name.
          SONAR_DEFAULT_BRANCH: master
          # Sonar token used to integrate with SonarCloud api.
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
